name: Check Link Integrity

on:
  schedule: [{cron: "42 2 * * 0"}]
  push:
    branches:
      - master
  pull_request:

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JustinBeckwith/linkinator-action@v1
