name: Generate Table of Contents

on:
  pull_request: {}

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}

      - name: Generate TOC for Markdown files
        run: |
          set -eux
          mkdir -p "${GITHUB_WORKSPACE}/.ci/"
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc -o ${GITHUB_WORKSPACE}/.ci/gh-md-toc
          chmod a+x ${GITHUB_WORKSPACE}/.ci/gh-md-toc
          TOC_MD_FILES=$(find . -name '*.md' -exec grep -l '<!--ts-->' {} \;)
          for md in $TOC_MD_FILES; do
            ${GITHUB_WORKSPACE}/.ci/gh-md-toc --insert --no-backup --hide-footer "$md"
          done

      - uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: |
            [lint] Generate Table Of Contents
